### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings

### ISSUE THREAD

**Issue by vmagdin** [oap-project/raydp#100]
It seems like there are multiple versions of SLF4J coming from Ray and PySpark, which lead to the following error being shown:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyspark/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

I'm using raydp in conjunction with the sparkmonitor project, which displays a progress bar for spark jobs, and this warning generates a lot of output which pollutes the results. Any suggestions for how to suppress this output or prevent it from happening in the first place?

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/6867120/110539478-27916d00-80da-11eb-8317-37f76bf9386c.png">

**Comment by ConeyLiu** [comment]
Hi @vmagdin, the problem has been fixed in the master branch. You may take a try.

**Comment by ConeyLiu** [comment]
Hi @vmagdin, you can try the nightly version `pip install raydp_nightly`.

**Comment by vmagdin** [comment]
Thanks, that works! Any idea when this will make it to a new release in pypi?

**Comment by ConeyLiu** [comment]
It should be released by the end of this month.
