### ISSUE TITLE
Unable to create nodes in an autoscaling cluster

### ISSUE THREAD

**Issue by vmagdin** [oap-project/raydp#104]
Hi there! I'm trying to figure out how to put together a proper Spark config in an auto-scaling cluster. 

I'm trying something very simple: 
```
import ray
import raydp

ray.init(address='auto')

spark = raydp.init_spark(
    'word_count',
     num_executors=16,
     executor_cores=5,
     executor_memory='1G'
)
```

I'm running this with an autoscaling config that starts with a single m4.16xlarge node (64 cores, 160GB RAM) and can auto-scale a few more worker nodes. However, I'm seeing the following error from the autoscaler:

```
Demands:
 {'memory': 20.0, 'CPU': 5.0}: 4+ pending tasks/actors
2021-03-12 23:24:25,447 WARNING resource_demand_scheduler.py:642 -- The autoscaler could 
not find a node type to satisfy the request: [{'CPU': 5.0, 'memory': 20.0}, {'CPU': 5.0, 'memory': 20.0}, 
{'CPU': 5.0, 'memory': 20.0}, {'CPU': 5.0, 'memory': 20.0}]. If this request is related to placement 
groups the resource request will resolve itself, otherwise please specify a node type with the
 necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
2021-03-12 23:24:25,559 INFO autoscaler.py:305 --
======== Autoscaler status: 2021-03-12 23:24:25.559754 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray-legacy-head-node-type
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 60.0/64.0 CPU
 11.72/163.184 GiB memory
 0.00/50.977 GiB object_store_memory

Demands:
 {'memory': 20.0, 'CPU': 5.0}: 4+ pending tasks/actors
```

I guess I have 2 questions about this:
* How does the requested amount of RAM translate into Ray demands? I asked for 1GB, but that seems to have translated to 20GB
* Any idea why the autoscaler can't fulfill the request? I've successfully used autoscaling on this cluster with Ray Tune.

Thanks for all the awesome work!

**Comment by ConeyLiu** [comment]
Hi @vmagdin

> How does the requested amount of RAM translate into Ray demands? I asked for 1GB, but that seems to have translated to 20GB

Here, the 20 means 20 memory units, the memory unit is `50 MB` in ray. 

> Any idea why the autoscaler can't fulfill the request? I've successfully used autoscaling on this cluster with Ray Tune.

The reason is ray can not auto-detect the memory resources if you do not specify in the yaml file. I have submitted the patch to ray upstream(https://github.com/ray-project/ray/pull/14567). There are two ways to work around this:
  1. Specified the `min_workers` to your expected one.
  2. Specified the `memory` in the `resource`. It should be 70% of the total available memory for the worker node.

**Comment by vmagdin** [comment]
Ok, thanks for the explanation!

I went with the 2nd option and specified `memory`:

```
available_node_types:
    cpu_16:
        node_config:
          InstanceType: m4.4xlarge
        resources: {"memory": 10_000_000_000}
        min_workers: 0
        max_workers: 16
```

And it looks like Ray is able to add machines of this type. However, there seems to be an error that's preventing jobs from actually running:

```
java.lang.IllegalArgumentException: A resource value should be an integer if it is greater than 1.0. Specified resource: memory = 190.72.
        at io.ray.api.options.BaseTaskOptions.<init>(BaseTaskOptions.java:29)
        at io.ray.api.options.ActorCreationOptions.<init>(ActorCreationOptions.java:27)
        at io.ray.api.options.ActorCreationOptions.<init>(ActorCreationOptions.java:9)
        at io.ray.api.options.ActorCreationOptions$Builder.build(ActorCreationOptions.java:161)
        at io.ray.api.call.BaseActorCreator.buildOptions(BaseActorCreator.java:121)
        at io.ray.api.call.ActorCreator.remote(ActorCreator.java:41)
        at org.apache.spark.raydp.AppMasterJavaUtils.createExecutorActor(AppMasterJavaUtils.java:54)
        at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$requestNewExecutor(RayAppMaster.scala:190)
        at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.$anonfun$schedule$1(RayAppMaster.scala:177)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$schedule(RayAppMaster.scala:176)
        at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint$$anonfun$receive$1.applyOrElse(RayAppMaster.scala:104)
        at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
        at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

This error came from calling the following code:
```
import ray
import raydp
import logging

ray.init(address='auto')

spark = raydp.init_spark(
    'word_count',
     num_executors=5,
     executor_cores=3,
     executor_memory=10_000_000_000,
     configs=configs
)
```

**Comment by ConeyLiu** [comment]
Hi @vmagdin, I am sorry for my mistake. I have reverted the problematic pr. The latest `raydp-nightly` should be OK now.

**Comment by vmagdin** [comment]
No worries, I pulled the latest from master and built it. It fixed the error I was seeing in the logs. However, I'm still not able to scale things out beyond the head node. 

My request for a certain kind of Spark cluster now triggers the autoscaler. For example, the following config 

```
spark = raydp.init_spark(
    'word_count',
     num_executors=16,
     executor_cores=5,
     executor_memory='5G'
)
```

Results in the following cluster state:

```
Node status
---------------------------------------------------------------
Healthy:
 1 cpu_64
 10 cpu_16  <---- 10 machines got autoscaled for the request
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 80.0/224.0 CPU
 79.69/258.203 GiB memory
 0.00/180.078 GiB object_store_memory

Demands:
 (no resource demands)
```

However, in none of my Spark jobs do I ever see the num cores go above 64, which is how many are present in the head node of my Ray cluster. In all runs (of varying difficulty), I never see more than 12 executors and 60 cores. Meanwhile I requested 16 executors, but adding those extra 4 would result in the workload spilling over to other machines in the cluster (which are actually available as you can see in the output). 

From the Spark UI:
<img width="2004" alt="Screen Shot 2021-03-15 at 10 13 18 PM" src="https://user-images.githubusercontent.com/6867120/111259596-765c6c80-85dc-11eb-98ea-ad38b60fd52a.png">

From the spark-monitor output:
<img width="1009" alt="Screen Shot 2021-03-15 at 9 55 19 PM" src="https://user-images.githubusercontent.com/6867120/111259607-7fe5d480-85dc-11eb-9c40-36437045d19b.png">

Any suggestions for how to trouble-shoot this?

**Comment by ConeyLiu** [comment]
Hi @vmagdin,

> However, in none of my Spark jobs do I ever see the num cores go above 64, which is how many are present in the head node of my Ray cluster. In all runs (of varying difficulty), I never see more than 12 executors and 60 cores. Meanwhile I requested 16 executors, but adding those extra 4 would result in the workload spilling over to other machines in the cluster (which are actually available as you can see in the output).

Do you mean all executors are running on the head node when the `num_executor` is smaller than 12? And ray requests an extra node when the `num_executor` is 16?

It does not trigger auto-scaling when the head node resources could satisfy the request, eg: 12 * 5 < 64. So all the executors will run on the head node. It needs to start up a new node when the remaining resources can not satisfy the request. Here we have started up 12 executors and occupied 60 cores, the head node only has 4 cores remaining which can not satisfy the one executor request(5 cores, 5 GB memory). So the auto scaler will start up a new node from the available node types.

**Comment by vmagdin** [comment]
> Do you mean all executors are running on the head node when the num_executor is smaller than 12? And ray requests an extra node when the num_executor is 16?

It seems to be the opposite. All the executors seem to be running on the head node even when num_executors > 12. In my example above, the following is happening:
* I request 16 executors * 5 cores =80 CPUs
* My head node has 64 cores, so the autoscaler spins up additional nodes
* The correct CPU usage (80 cores) seems to be reflected in `ray status` -- `80.0/224.0 CPU`
* __However__, according to Spark UI, there are only 12 executors / 60 cores (which is the max that would fit on the head node).

**Comment by ConeyLiu** [comment]
OK, it seems like the ray spark actor has started up while the spark executor is not registered with the spark driver. Are there any logs that show the timeout exceptions?

What happens when you set the min_worker to 1 in this case?

**Comment by vmagdin** [comment]
I realized I was doing something silly .. I wasn't installing RayDP on worker nodes :)

I'm now seeing executors on worker nodes.
