### ISSUE TITLE
Accessing files in S3 with Spark's S3A connector

### ISSUE THREAD

**Issue by vmagdin** [oap-project/raydp#110]
Hi there,

I'm trying to use RayDP on an EC2 Ray cluster. It took me some time to figure out how to access S3 correctly. The solution involved downloading a custom version of Spark (with Hadoop 3), and then downloading some AWS jars:

```
# Install a custom version of PySpark which plays nicely with S3
wget 'https://mirrors.ocf.berkeley.edu/apache/spark/spark-3.0.2/spark-3.0.2-bin-hadoop3.2.tgz'
tar -xvzf spark-3.0.2-bin-hadoop3.2.tgz
pushd spark-3.0.2-bin-hadoop3.2/python/
python setup.py sdist
pip install dist/pyspark-3.0.2.tar.gz
popd

# Install the Spark-on-Ray project
pip install raydp-nightly

# Get the S3 connector for Spark
pushd "$(python -c 'import os, pyspark; print(os.path.dirname(pyspark.__file__))')/jars"
wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar
wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.375/aws-java-sdk-bundle-1.11.375.jar
popd
```

As a result of this, I am able to use the S3A connector to do things like `spark.read.parquet("s3a://.....")`. This connector automatically figures credentials from the head node's instance role, so no explicit authentication is needed.

However, when I try to do the same in an auto-scaling cluster, the worker nodes are not able to get the credentials. The following error shows up:

```
Py4JJavaError: An error occurred while calling o166.json.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 71 in stage 0.0 failed 4 times, 
most recent failure: Lost task 71.3 in stage 0.0 (TID 88, 172.31.38.110, executor 12): 
java.nio.file.AccessDeniedException: <<BUCKET_NAME>>: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: 
No AWS Credentials provided by SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider 
InstanceProfileCredentialsProvider : com.amazonaws.SdkClientException: The requested metadata is not
 found at http://xxx.xxx.xxx.xxx/latest/meta-data/iam/security-credentials/
```

I guess this problem is related to this one: https://github.com/ray-project/ray/issues/3115.

However, I am wondering if there's any workaround specific to RayDP that could help with this issue.

**Comment by ConeyLiu** [comment]
Have you tried this: https://medium.com/@bogdan.cojocar/how-to-read-json-files-from-s3-using-pyspark-and-the-jupyter-notebook-275dcb27e124 ?

**Comment by vmagdin** [comment]
Thanks for the link! I ended up solving the problem by explicitly setting the `IamInstanceProfile` field in the cluster YAML file for worker nodes. It's not ideal, but in my case I also needed to access S3 during worker node creation, so I went with this solution to deal with both issues.
