### ISSUE TITLE
[SDLe]Vulnerabilities found during SDLe

### ISSUE THREAD

**Issue by HongW2019** [oap-project/raydp#117]
1.	Bump com.fasterxml.jackson.core:jackson-databind version.
2.	Bump org.glassfish.jersey.core:jersey-server version.
3.	Specify the Scala version.
![image](https://user-images.githubusercontent.com/30172512/113232303-7bedce00-92cf-11eb-963c-77bd353e371b.png)
![image](https://user-images.githubusercontent.com/30172512/113232316-7f815500-92cf-11eb-9e36-723add7cc515.png)
![image](https://user-images.githubusercontent.com/30172512/113232323-8314dc00-92cf-11eb-9f65-87a1363f78c2.png)

**Comment by kira-lin** [comment]
Thanks, closing issue.
