### ISSUE TITLE
Spark 3.1.0+ not compatible

### ISSUE THREAD

**Issue by kira-lin** [oap-project/raydp#121]
Setting spark version to 3.1.0+ in `pom.xml` of core will result in this:
```
[ERROR] /home/lzhi/Projects/raydp/core/src/main/scala/org/apache/spark/scheduler/cluster/raydp/RayCoarseGrainedSchedulerBackend.scala:196: error: method doRequestTotalExecutors overrides nothing.
[ERROR] Note: the super classes of class RayCoarseGrainedSchedulerBackend contain the following, non final members named doRequestTotalExecutors:
[ERROR] protected def doRequestTotalExecutors(resourceProfileToTotalExecs: Map[org.apache.spark.resource.ResourceProfile,Int]): scala.concurrent.Future[Boolean]
[ERROR]   override protected def doRequestTotalExecutors(requestedTotal: Int): Future[Boolean] = {
```
@ConeyLiu

**Comment by ConeyLiu** [comment]
It seems like spark 3.1.0 and above have changed the `CoarseGrainedSchedulerBackend` interface. We should limit the pyspark version.

**Comment by kira-lin** [comment]
Yes, I've submitted a pr to revert it.

**Comment by carsonwang** [comment]
If we just build our jar with Spark 3.0.0 but run it with pyspark 3.1, does it work?

**Comment by kira-lin** [comment]
> If we just build our jar with Spark 3.0.0 but run it with pyspark 3.1, does it work?

It actually works. We've been doing this in CI for a few days.
