### ISSUE TITLE
RayDP : Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources 

### ISSUE THREAD

**Issue by SnehaHegde24** [oap-project/raydp#129]
Hi ,

First of all thanks for this  implementation which is of great use .

I am a beginner to this ,  facing below issue  when i am trying to execute raydp on minikube with cpu 10 and memory 10GB 

 **Is there any explict memory that needs to be set , because for any action execution in spark i get the following issue** 
21/04/07 05:02:09 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

Any help is greatly appreciated  👍

**Comment by ConeyLiu** [comment]
Hi @SnehaHegde24, which version of ray and raydp are you using? And can you show me how you submit your job?

**Comment by SnehaHegde24** [comment]
Hi @ConeyLiu  , 

Ray version : 1.2.0 

RayDP version : latest 
![image](https://user-images.githubusercontent.com/16030241/114133829-4a56b180-9924-11eb-819e-57a523fb378b.png)

I have created a yaml file to submit job referring to docker container containing  the following in the image
ray image + raydp + java(15) 

And job has this memory reference explicitly 👍 
![image](https://user-images.githubusercontent.com/16030241/114150676-f3f46d80-9939-11eb-8d72-13dba0f1204c.png)

**Comment by ConeyLiu** [comment]
Do you use ray autoscaler?  Could you show your tried code?

**Comment by jdortuzar5** [comment]
Hello, I'm also running into this issue. The thing is that I'm trying to run it locally, do you have any tips or advice?

**Comment by ConeyLiu** [comment]
Hi @jdortuzar5, could you provide more details? Such as ray version, raydp version, the code you tried?

**Comment by jdortuzar5** [comment]
@ConeyLiu I'm using Ray 1.3.0, RayDP 0.2.0, PySpark 3.0.2. I'm trying to load a simple CSV file locally, here is the code I'm using:
```
import raydp
import ray

ray.init()
spark = raydp.init_spark('data_transform',
                        num_executors=1,
                        executor_cores=1,
                        executor_memory='4GB',
                         )

df = spark.read.format("csv").option("header", "true").load("app/timeSeries (15).csv")
print(df.describe())
```
I believe my problem comes from the Java configuration, to make sure, I'm using the docker image to run the same code. But any help is more than welcome.

**Comment by jdortuzar5** [comment]
I've manage to run the script inside a docker container, so the issue was in fact my Java configuration. Thanks for the help!

**Comment by ConeyLiu** [comment]
thanks for the feedback.
