### ISSUE TITLE
Raydp package is not installed on ray:1.3.0 image

### ISSUE THREAD

**Issue by hglyou** [oap-project/raydp#144]
Hi, 

I'm trying to use raydp with Ray client mode and I found the below issue as a guide. 
https://github.com/oap-project/raydp/issues/130

The issue suggests I should instantiate SparkSession within Ray worker's context, but as I tried it, an error occurred telling me that raydp is not installed on worker nodes. 

Is this intended? Should I install raydp pacakges on all Ray worker nodes?

**Comment by ConeyLiu** [comment]
Yes, you need to install it. `ray:1.3.0` is an image for the ray not include other libraries.

**Comment by hglyou** [comment]
Thank you for answering!
