### ISSUE TITLE
Support Spark application web UI

### ISSUE THREAD

**Issue by zuston** [oap-project/raydp#150]
Thanks for the great work!

When i try to run spark wordcout programming with raydp, i can't find the Spark application web ui.
Doesn't it support spark web ui yet?

**Comment by kira-lin** [comment]
Hi,
WebUI should be working after you run `raydp.init_spark`. By default it is at localhost:4040. Can you run
```python
import ray,raydp
ray.init()
spark=raydp.init_spark("foo",1,1,"500m")
```
in REPL, and check if WebUI is up in your browser before your call `spark.shutdown()`?
Thanks

**Comment by zuston** [comment]
Thanks for your quick reply. It works! @kira-lin 
Besides it's better to print the web ui url in the client output. 
Maybe i can submit first PR to support it.

**Comment by kira-lin** [comment]
Spark will print it in its log as 'INFO'. By default logLevel is 'WARN', so you did not see it.

**Comment by zuston** [comment]
Thanks! 
We have a scenario that we need to use both Spark and TensorFlow for iterative training on Ray. 
Hence we want to use raydp online, and would like to ask if raydp is used in online environments at scale?

**Comment by carsonwang** [comment]
@zuston , this sounds like a very good scenario that fits RayDP usage. A few other users are currently also working on evaluating RayDP and integrating it in their use cases. The scalability should not be a problem as Spark on Ray still uses Spark's own communication protocol. We can work together for any issues/requests you may have.
Can you also share a little more about your scenario? Are you using RaySGD or Horovod for distributed Tensorflow training? Is it on CPU or GPU?

**Comment by zuston** [comment]
@carsonwang Thanks.

Scenario:
tensorflow training -> spark etl embedding -> tensorflow training -> spark etl embedding

So it will like as follows:
```python
for  index in range(10):
    tf_train()
    spark_etl()
```

Because of reusing the users' tf estimator code, we will run tf training on Ray with custom mode not using RaySGD, which will build tensorflow cluster for training. 
And then to reuse the existing ML system, ray will be launched on Yarn by linkedin/TonY.

Besides for now, only CPU will be used on this scenario. And Horovod will be not on Ray, it can be directly on Yarn by TonY.

Any ideas on it?

**Comment by carsonwang** [comment]
Thanks for the information! Sounds great! We are also working with the Ray community to better support Ray on Yarn. Will also take a look at the linkedin/TonY option as you mentioned.

**Comment by zuston** [comment]
Wow. 
Maybe we could have a talk about it. RayDP has slack group?

**Comment by carsonwang** [comment]
@zuston , I created a channel in Ray slack for discussion and sent an invitation to your email. Please see if you receive it. Otherwise please try to join the Ray slack first.

**Comment by zuston** [comment]
Done. Thanks @carsonwang
