### ISSUE TITLE
Can you provide support for ray version 1.6.0? 

### ISSUE THREAD

**Issue by YeahNew** [oap-project/raydp#174]
Recently, I need to use the latest Dataset APIs in ray 1.6.0 version. However, it is found that raydp-nightly only supports ray 1.4.2 version. If I start the ray cluster, I cannot connect to the cluster using raydp.init_spark(). When can raydp support ray 1.6.0? 
Thanks~

**Comment by carsonwang** [comment]
Thanks for the feedback. Ray java 1.6.0 is still not available on maven. We will work with Ray community and then support it in RayDP.
