### ISSUE TITLE
Can rayDP be used for Spark mllib? 

### ISSUE THREAD

**Issue by YeahNew** [oap-project/raydp#186]
I am very happy to see the application of rayDP in the field of data processing and deep learning, but in many cases the data obtained by deep learning needs to be passed to traditional machine learning algorithms for classification and other operations. The algorithm in Spark mllib can be well modeled based on mini-batch, so can Spark mllib implement classifier modeling based on mini-batch through rayDP?

**Comment by carsonwang** [comment]
Yes, it will be executed in a distributed manner on Ray. After you create a Spark session with RayDP, you will have Spark executor running in different node in the Ray cluster. There is no need to manually setup the Spark cluster. There is no difference for using Spark MLLib when it runs on Ray. Just try any existing Spark MLlib examples from Spark document and feedback if you find something doesn't work on Ray.
