### ISSUE TITLE
WordCount on RayDP

### ISSUE THREAD

**Issue by Second222None** [oap-project/raydp#194]
How to write a **wordcount** test based on HDFS? The following code doesn't work.

```python
import sys
from operator import add
import pyspark
import ray
import raydp

#
# Adopted from spark's example: https://spark.apache.org/examples.html
#
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print >> sys.stderr, "Usage: wordcount <HDFS_INPUT> <HDFS_OUTPUT>"
        exit(-1)
    ray.init(address='auto', _redis_password='5241590000000000')
    sc = raydp.init_spark('PythonWordCount',
                         num_executors=2,
                         executor_cores=10,
                         executor_memory='2G')
    lines = sc.textFile(sys.argv[1], 1)
    counts = lines.flatMap(lambda x: x.split(' ')) \
                  .map(lambda x: (x, 1)) \
                  .reduceByKey(add)
    counts.saveAsTextFile(sys.argv[2])

    raydp.stop_spark()
```

**Comment by carsonwang** [comment]
`raydp.init_spark` returns a SparkSession instead of a SparkContext. You can use `spark.read.text` API, for example
```
spark = raydp.init_spark(...)
lines = spark.read.text(...)
```

**Comment by Second222None** [comment]
Are there instructions for using the raydp API?

**Comment by carsonwang** [comment]
You only need to call `raydp.init_spark` to create a SparkSession. After that, just follow pySpark API to write the Spark program. Is there any specific problem you have when calling `raydp.init_spark`?

**Comment by Second222None** [comment]
Thank you! I see. I have read the content from **hdfs** successfully. 
Now I can use it like Spark.

**Comment by carsonwang** [comment]
Glad to see it works. I'll close this one. Please feel free to open new issues if you have any question.
