### ISSUE TITLE
Can not use raydp with remote clusters

### ISSUE THREAD

**Issue by rseed42** [oap-project/raydp#195]
I am having difficulties making raydp work with a remote cluster. It looks that there is a bug when trying to configure the Spark cluster. It works with `ray.init()` as a local instance, but it does not work with `ray.init(address='ray://xxx.xxx.xxx.xxx:10001')`:

```python
    self._spark_cluster = SparkCluster(self._configs)
  File "/home/ven/miniconda3/envs/ray/lib/python3.9/site-packages/raydp/spark/ray_cluster.py", line 34, in __init__
    self._set_up_master(None, None)
  File "/home/ven/miniconda3/envs/ray/lib/python3.9/site-packages/raydp/spark/ray_cluster.py", line 40, in _set_up_master
    self._app_master_bridge.start_up()
  File "/home/ven/miniconda3/envs/ray/lib/python3.9/site-packages/raydp/spark/ray_cluster_master.py", line 56, in start_up
    self._set_properties()
  File "/home/ven/miniconda3/envs/ray/lib/python3.9/site-packages/raydp/spark/ray_cluster_master.py", line 145, in _set_properties
    options["ray.node-ip"] = node.node_ip_address
AttributeError: 'NoneType' object has no attribute 'node_ip_address'
 ```
Package versions are as follows:

- ray==1.8.0

- raydp==1.4.0

Started ray as usual:

```
ray start --head --port=6379
ray start --address='192.168.178.20:6379' --redis-password='5241590000000000'
```

Stepping through the debugger, the `node` variable is not initialized when using the remote address (`ray.init("ray://...:10001")`), but it is initialized when ray is started locally  with `ray.init()`:

![Bug Report](https://user-images.githubusercontent.com/962863/140813071-990cd0dd-bb69-42a6-90bb-e724bb455edc.png)

I tried a few combinations of versions for `raydp` and `ray`, but this problem persist. I am not sure what is exactly wrong, because if this is true, there is no way raydp works with a remote cluster.

Any ideas?

**Comment by kira-lin** [comment]
Hi, @rseed42 thanks for trying raydp! 
Currently, we start a java process on local machine to connect to ray. This does not work if you use ray client. Can you try to put raydp.init_spark in an actor?
Like this:
```python
@ray.remote
    class SparkRemote:
        def __init__(self):
            self.spark = raydp.init_spark(app_name="test_spark_remote",
                                          num_executors=1,
                                          executor_cores=1,
                                          executor_memory="500MB")

        def run(self):
            return self.spark.range(0, 100).count()

        def stop(self):
            self.spark.stop()
            raydp.stop_spark()
```

**Comment by kira-lin** [comment]
In addition, please use ray 1.7.0 with raydp 0.4.0.

**Comment by rseed42** [comment]
@kira-lin Many thanks for your explanation! I tested it and it works fine :). I will try to contribute to the official ray documentation once I get a bit deeper understanding (it was lacking this part in the Spark on Ray section). I think that raydp can potentially be a big argument for the adoption on Ray, so congrats on doing a great job!

**Comment by Bowen0729** [comment]
> Hi, @rseed42 thanks for trying raydp! Currently, we start a java process on local machine to connect to ray. This does not work if you use ray client. Can you try to put raydp.init_spark in an actor? Like this:
> 
> ```python
> @ray.remote
> class SparkRemote:
>     def __init__(self):
>         self.spark = raydp.init_spark(app_name="test_spark_remote",
>                                       num_executors=1,
>                                       executor_cores=1,
>                                       executor_memory="500MB")
> 
>     def run(self):
>         return self.spark.range(0, 100).count()
> 
>     def stop(self):
>         self.spark.stop()
>         raydp.stop_spark()
> ```

seems like all spark executors will run on single node, what if I want it to schedule executors on multiple nodes?
