### ISSUE TITLE
Why all spark executors running on a single node in a ray cluster?

### ISSUE THREAD

**Issue by Bowen0729** [oap-project/raydp#199]
connect to a ray cluster:
ray.init(address = 'ip:6379') 

create a spark session on ray:
spark = raydp.init_spark("test",  num_executor=6, executor_memeory='5G')

and all the spark executors(ray actors) are running on single node

I hope that the executors will distributed among all nodes

what should I do?

**Comment by carsonwang** [comment]
Can you try running `raydp.init_spark` in an actor and does that work? https://github.com/oap-project/raydp/issues/195#issuecomment-963732609

**Comment by Bowen0729** [comment]
> Can you try running `raydp.init_spark` in an actor and does that work? [#195 (comment)](https://github.com/oap-project/raydp/issues/195#issuecomment-963732609)

Thank you for your reply.

I tried, but not worked.

I'm the first time user for ray and raydp, I start ray cluster on yarn, when I run raydp.init_spark, I saw two jobs on ray dashboard, one job contains my SparkRemote actor, the other one contains all spark executors which belong to the same node. and some of them are in 'PENDING_CREATION' state.

**Comment by carsonwang** [comment]
Does your issue specific to Ray on Yarn or not? How did you run Ray on Yarn, using the existing functionality in Ray or your own implementation? Do other tasks/actors running on multiple nodes correctly?

**Comment by Bowen0729** [comment]
**_How did you run Ray on Yarn, using the existing functionality in Ray or your own implementation?_**

I run Ray on Yarn via skein, and my skein config file like this:

name: ray-on-yarn
services:
    ray-head:
        instances: 1
        resources:
            vcores: 10
            memeory: 50GiB
         files:
            environment: my-conda-env.tag.gz
          script: |
              source envirnment/bin/activate
              skein kv put --key RAY_HEAD_ADDRESS --value $(hostname -i) current
              ray start --head --port 6379 --include-dashboard true --dashboard-host $(hostname -i) --block 
    ray-worker:
        instances: 2
        resources:
            vcores: 20
            memeory: 50GiB
         files:
            environment: my-conda-env.tag.gz
         script: |
              source envirnment/bin/activate
              sleep 10
              RAY_HEAD_ADDRESS=$(skein kv get --key RAY_HEAD_ADDRESS current)
              ray start --adress $RAY_HEAD_ADDRESS:6379 --block

And then skein submit to yarn, I can get a ray cluster with 3 nodes and saw them on ray dashboard

For other questions I need some tests, Thank you for your reminder

**Comment by Bowen0729** [comment]
> Does your issue specific to Ray on Yarn or not? How did you run Ray on Yarn, using the existing functionality in Ray or your own implementation? Do other tasks/actors running on multiple nodes correctly?

I test the raydp on native ray cluster, and the executors distributed among all nodes.
It seems like that ray on Yarn has some mistake in my way

**Comment by Bowen0729** [comment]
one of the raylet:
Error: Could not find or load main class io.ray.runtime.runner.worker.DefaultWorker

**Comment by kira-lin** [comment]
> Error: Could not find or load main class io.ray.runtime.runner.worker.DefaultWorker

**Comment by Bowen0729** [comment]
> > Error: Could not find or load main class io.ray.runtime.runner.worker.DefaultWorker
> 
> When does this error happen? In native ray cluster or ray on yarn? Maybe ray java is not installed, or the classpath is wrong


**_In native ray cluster or ray on yarn_**

On Yarn.

**_When does this error happen?_**

when I run raydp.init_spark, some executors on node1 started well, and other executors on node2 is on PENDING_CREATION state, I think these executors(that is actors) lead to this ERROR.

but When I specify actor on node2, such as this:
@ray.remote(resources={"node:node2": 0.1})
the executors worked well on node2, and didn't has the ERROR

**Comment by kira-lin** [comment]
We have not tried ray on yarn, so maybe we cannot help. The error means ray cannot find its java runtime, and thus cannot start ray java workers. 

> @ray.remote(resources={"node:node2": 0.1})

This is python workers, right? So the problem is in java part. Can you check the ray logs, and find the error, verify it?

**Comment by Bowen0729** [comment]
> We have not tried ray on yarn, so maybe we cannot help. The error means ray cannot find its java runtime, and thus cannot start ray java workers.
> 
> > @ray.remote(resources={"node:node2": 0.1})
> 
> This is python workers, right? So the problem is in java part. Can you check the ray logs, and find the error, verify it?

Thank you for your reply.

I guess I find where is the problem.

executor started via 'java -cp -DClassPath io.ray.runtime.runner.worker.DefaultWorker', and ClassPath is the absolute path, but my ray cluster is on yarn, the file resources on hdfs, they don't have the same absolute path.

such as, raydp.jar is on HADOOP_DATA_DIR/nm/..../CONTAINER_NAME/environment/lib/python3.7/site-packages/raydp/jars/ on one ray worker, but they are on different container for other ray workers, so  java -cp cannot find the io.ray.runtime.runner.worker.DefaultWorker

and what shoud I do? Can I specify some conf to aviod it?

**Comment by kira-lin** [comment]
Yes, that's the problem, and I'm afraid that there is no available solution. AFAIK, Ant tried to run Ray on Yarn before, but that is no longer maintained. You can try in native ray cluster

**Comment by Bowen0729** [comment]
I want to set config spark.executor.extraClassPath, but it not effective

**Comment by Bowen0729** [comment]
Can I use RayOnSpark to get a ray cluster and then use raydp on this ray cluster? that seems a little wired

**Comment by kira-lin** [comment]
Because Spark executors run in java worker, but ray fails to start java workers due to classpath. This feature needs to modify ray to be able to read jar in hdfs. This might be possible with new runtime_env, but it is still under development now.

> Can I use RayOnSpark to get a ray cluster and then use raydp on this ray cluster? that seems a little wired

I'm not sure if it is possible...

**Comment by Bowen0729** [comment]
OK, thank you. We only have a bigdata cluster without a ray cluster, which bothers me so much

**Comment by Bowen0729** [comment]
how can I configure the ray.job.code-search-path, I found it in ray docs

**Comment by kira-lin** [comment]
Do you want to configure a hdfs path? I don't think hdfs path is going to work. Anyway, you can try it, just provide in the configs in init_spark function.

**Comment by Bowen0729** [comment]
I want to Specify the local path for a test.
not worked, I think I should specify the local path in the classpath. Is there any way I can configure the classpath?

**Comment by kira-lin** [comment]
You would have to modify the python files, add the local path in function `_prepare_jvm_classpath`

**Comment by Bowen0729** [comment]
Got it, thank you very much

**Comment by Bowen0729** [comment]
Change the classpath to the local path worked..... the executors distributed among all nodes

I guess I should download the jar from the hdfs for the first time, and then specify the local jar path

BTW, does the community  consider exposing the classpath parameter, that user will specify there extra classpath?

**Comment by kira-lin** [comment]
> BTW, does the community consider exposing the classpath parameter, that user will specify there extra classpath?

This should be simple. Do you want to contribute a PR?

**Comment by Bowen0729** [comment]
Of course, I would open a PR in the next few days.

**Comment by kira-lin** [comment]
> ray.data.from_spark() method will collect the data to the driver?

No, executors will write data to ray respectively, and only object refs will be collected to master.

writer,writeBatch OOM is more tricky, Can you provide more information? Increasing ray object store memory might not work, since writer.writeBatch does not write data to object store. It is actually serializing dataframe to arrow stream IPC format, so that it can be read by python. You should first try increasing executor memory.

**Comment by Bowen0729** [comment]
I increase the parallelism of ray.data.from_spark(), and now it works fine with the same executor memory, does it mean that the data of each partation is too big, so writer.writeBatch for each partation OOM, and how can I determine the parallelism number for other situations?

**Comment by kira-lin** [comment]
By increasing the parallelism number, we will also repartition the dataframe. When converting the dataframe(in jvm) to ray dataset(in python), we need to first convert the spark dataframe to arrow data, one partition at a time. This will take up some extra memory, around the size of one partition of dataframe

**Comment by Bowen0729** [comment]
I see. Thank you for your patient explain

**Comment by kira-lin** [comment]
We are now using 1 to 1 mapping from spark dataframe partition to ray dataset block. It's also possible to do 1:N mapping, what do you think? Is it necessary?

**Comment by Bowen0729** [comment]
I have no idea, but actually you can do that and let users choose 1:1 or 1:N mapping

**Comment by james-tn** [comment]
I suggest that the raydp.executor.extraClassPath parameters be in the form of a list of jars with comma as separator to support adding multiple paths. In my case, I needed to customize ray, raydp and pyspark paths to jars. This is to support custom cluster setup where driver configuration can be different from worker.

**Comment by Bowen0729** [comment]
https://github.com/ray-project/ray/pull/24170
ray support add jars in runtime env for Java , I think this issue can be optimized with this feature.
