### ISSUE TITLE
Spark UI executor page is empty

### ISSUE THREAD

**Issue by marin-ma** [oap-project/raydp#202]
![image](https://user-images.githubusercontent.com/52736607/149440515-afd5a477-056b-4694-9a3e-fd8390cdd05f.png)

It returns an error:

HTTP ERROR 500 java.lang.NoSuchMethodError: org.glassfish.jersey.server.ServerExecutorProvidersConfigurator.registerExecutors(Lorg/glassfish/jersey/internal/inject/InjectionManager;Lorg/glassfish/jersey/model/internal/ComponentBag;Lorg/glassfish/jersey/spi/ExecutorServiceProvider;Lorg/glassfish/jersey/spi/ScheduledExecutorServiceProvider;)V

**Comment by kira-lin** [comment]
I guess it's included in our pom due to SparkSubmit? Delete it if we can, otherwise upgrade it.
