### ISSUE TITLE
add spark read hive support

### ISSUE THREAD

**Issue by hezhaozhao-git** [oap-project/raydp#220]
### issue
When I use raydp's spark to read hive, the error 'not found table or view' is reported. Looking at the source code, it is found that the read does not support enableHiveSupport by default. 
The relevant code is in [ray_cluster.py](https://github.com/oap-project/raydp/blob/master/python/raydp/spark/ray_cluster.py)

### Are you willing to submit a PR?
Yes I am willing to submit a PR!

**Comment by kira-lin** [comment]
Thanks, closing this issue
