### ISSUE TITLE
[Feature]Support for Ray 1.12.0 ?

### ISSUE THREAD

**Issue by tianlinzx** [oap-project/raydp#228]
[Feature]Support for Ray 1.12.0 since it is officially released ?

**Comment by kira-lin** [comment]
It seems like 1.12.0 has not finalized. We'll see if we can support it with the latest patch. Thanks

**Comment by tianlinzx** [comment]
@kira-lin 1.12.0 is now finalized . would you please officially support it ?

**Comment by kira-lin** [comment]
Hi @tianlinzx , we'll soon release 0.4.2 to support it. The PR is ready.

**Comment by kira-lin** [comment]
We have released 0.4.2, please reopen it if you still have issues.
