### ISSUE TITLE
[Enhancement] Improve logging configuration 

### ISSUE THREAD

**Issue by kira-lin** [oap-project/raydp#236]
Right now,  the native spark way to configure the logging level does not work. We need to fix it.
Update README if necessary.

**Comment by Hoeze** [comment]
+1 on that. I get a lot of unnecessary INFO logs in my cell output that I do not get with plain spark.
Would be quite helpful to have a possibility to turn these off.

**Comment by carsonwang** [comment]
This has been resolved by #269
