### ISSUE TITLE
RayDP on Databricks

### ISSUE THREAD

**Issue by LAITRUNGMINHDUC** [oap-project/raydp#254]
Hi all,

I read on Databricks websites - and I learn about RayDP: https://databricks.com/session_na21/build-large-scale-data-analytics-and-ai-pipeline-using-raydp

I tried to make this example works, but the system crash at the first line: 
`spark = raydp.init_spark(......)`

The error keeps saying:` "java gateway process exited before sending its port number".`

Could you please share your thinking on how I could setup RayDP on Databricks?
Thank you so much.

My current system:
- 1 clusters: 1 driver - 2 workers
- CPU: 8 cores - RAM 32GB for each node
- Spark 3.2.1

**Comment by carsonwang** [comment]
Hi @LAITRUNGMINHDUC, did you start a Ray cluster on a Databricks Spark cluster and then want to use RayDP? RayDP is Spark on Ray so it makes it look like Spark on Ray on Spark. Usually you can just start a Ray cluster in cloud and use RayDP to run the Spark program and connect with other Ray components. Could you please share more about your use case that you want to run on Databricks?

**Comment by LAITRUNGMINHDUC** [comment]
Oo

**Comment by kira-lin** [comment]
hi @LAITRUNGMINHDUC ,
RayDP does not has its own SQL implementation for now, I think the performance would be very similar to vanilla spark. If you want to have better SQL performance, maybe you can try our another project, gazelle.

I can't identify the problem with the error you provide. Can you please run ps aux| grep raydp, and shutdown the related process(a java process, main class is AppMasterEntryPoint), then try again? And what's your ray and spark version?

**Comment by benedikt-mue** [comment]
Hi @kira-lin.
I am facing the same issue having the same setup. I just want to convert a Spark dataframe into a Ray datasets for downstream model training. Is there a way to do it in this setup?

**Comment by kira-lin** [comment]
close as stale
