### ISSUE TITLE
How to use hive in Spark on RayDp？

### ISSUE THREAD

**Issue by Writer-X** [oap-project/raydp#263]
An error occurs when I use “spark = raydp.init_spark(...,enable_hive=True)”, I want to make sure that ray1.13.0 and raydp0.4.2 support this 
feature?

**Comment by Writer-X** [comment]
Using raydp-nightly fixed this problem

**Comment by carsonwang** [comment]
hi @Writer-X, Thanks for the update!

**Comment by Writer-X** [comment]
hi @carsonwang, I  encountered an error when using this sample.

`
import ray
import raydp
ray.init("auto")
spark = raydp.init_spark(app_name="RayDP Example",
                         num_executors=2,
                         executor_cores=2,
                         executor_memory="4GB")

# Spark Dataframe to Ray Dataset
df1 = spark.range(0, 1000)
ds1 = ray.data.from_spark(df1)
`

The error is as follows：
![image](https://user-images.githubusercontent.com/80471801/186422600-a9a70fd9-8a43-4165-a75f-15a42f094d37.png)


I use the Ray cluster deployed on the K8S cluster. Could you give me some suggestions?

**Comment by kira-lin** [comment]
This error indicates that the Raydp Jar is not included in the pyspark driver's classpath for some reason. Can you check driver_cp in ray_cluster.py and see if it is a valid path where the driver is run?

**Comment by Writer-X** [comment]
Thank you for your advice. I have corrected the above error by modifying rayDP_cp in ray_cluster.py, but there is still a new error.

![1280X1280](https://user-images.githubusercontent.com/80471801/187171797-58a40436-d42e-4621-80f6-26b20f32f328.PNG)

I use spark3.2.2. Maybe I'm using the wrong version of Spark?

**Comment by kira-lin** [comment]
Are you using java 9? In our tests, we use java 8 and spark 3.2.1, you can try this configuration. Can you use pyspark to start a session without raydp?

**Comment by Writer-X** [comment]
I'm using JAVA8. After the Spark version is changed to 3.2.1, this problem is not fixed. The initialization is still the same as the sample mentioned above.
`spark = raydp.init_spark(app_name="RayDP Example",
                         num_executors=2,
                         executor_cores=2,
                         executor_memory="4GB")`

**Comment by kira-lin** [comment]
https://stackoverflow.com/questions/57519804/using-jackson-2-9-9-in-java-spark

Maybe this link helps. I'm not sure if this error is related to RayDP

**Comment by kira-lin** [comment]
close as stale
