### ISSUE TITLE
Scala, Java & R APIs

### ISSUE THREAD

**Issue by SebastienDorgan** [oap-project/raydp#264]
Is it possible to use a spark cluster created with RayDP via Scala, Java & R APIs?

**Comment by carsonwang** [comment]
Yes, you can use raydp-submit (similar to spark-submit) to submit an application to the Spark cluster created by RayDP. Please see https://github.com/oap-project/raydp/blob/master/doc/spark_on_ray.md#spark-submit 
Please let us know if you encounter any problem.

**Comment by SebastienDorgan** [comment]
Great, thank you very much!
