### ISSUE TITLE
Ray 2.0 Support

### ISSUE THREAD

**Issue by tianlinzx** [oap-project/raydp#266]
Since Ray2.0 is released, will ray 2.0 be officially supported ?

**Comment by kira-lin** [comment]
We are look into this, thanks for opening the issue

**Comment by joyliu329** [comment]
How's it going? I can't wait ~

**Comment by kira-lin** [comment]
@joyliu329 thanks for your patience. We have already merged the support for ray 2.0, you can try our nightly. We'll release a official version very soon.

**Comment by carsonwang** [comment]
Ray 2.0 is supported in RayDP 5.0.0. Thanks for the patience. I will close this one. Please feedback if you have any new request or issue.
