### ISSUE TITLE
Two RayAppMaster actors launched?

### ISSUE THREAD

**Issue by jerryzhou3** [oap-project/raydp#272]
It seems to me that raydp spark has two RayAppMaster actors launched, one launched in python/raydp/spark/ray_cluster.py with the RayDPSparkMaster class using the Java bridge, and another launched in core/src/main/scala/.../RayCoarseGrainedSchedulerBackend.scala.

Is my understanding correct? If so, what is the purpose of launching two RayAppMaster?

Thanks!

**Comment by kira-lin** [comment]
The one in RayCoarseGrainedSchedulerBackend get launched only when using raydp-submit. In that case, there are no python app, thus no java bridge. In fact, it is added when implementing raydp-submit. So these two never get launched at the same time.

**Comment by jerryzhou3** [comment]
That resolves my confusion. Thank!
