### ISSUE TITLE
Add predict api to estimator

### ISSUE THREAD

**Issue by buaazhwb** [oap-project/raydp#50]
For now, user can only obtain predictions by getting the model and then predicting

**Comment by ConeyLiu** [comment]
what input and output should we want? And for predicting, does it should be the model serving part?

**Comment by buaazhwb** [comment]
I'm not sure whom raydp's target user is.  Looks like the evaluate function is enough. 
If I'm a kaggler,  I need the prediction result of test dataset which is without label and submit the result to the competition. For now, I need to get the model and predict by myself.
The purpose of predicting is different from serving. We just want to obtain the prediction in a python script

Input should support both RayDp dataset and spark dataframe. For output, should it be consistent with input or just numpy array/pandas dataframe?

**Comment by kira-lin** [comment]
close as stale
