### ISSUE TITLE
examples/pytorch_dlrm.ipynb markdown format

### ISSUE THREAD

**Issue by offthewall123** [oap-project/raydp#90]
https://github.com/oap-project/raydp/blob/master/examples/pytorch_dlrm.ipynb

This example's markdown format not correct,
"cell_type": "raw" => "cell_type": "markdown",

@carsonwang

**Comment by ConeyLiu** [comment]
You mean the Copyright, right? Will update it.

**Comment by offthewall123** [comment]
Yes.

**Comment by ConeyLiu** [comment]
Fixed in #92
